// Code generated by "gogen option"; DO NOT EDIT.
// Exec: "gogen option -n CommandSetOption -o gen_options_commandset.go"
// Version: 0.0.4

package promptx

var _ = promptxCommandSetOptions()

// CommandSetOptions command set options
// generate by https://github.com/aggronmagi/gogen/
type CommandSetOptions struct {
	// comman set name
	Name string
	// command set commands
	Cmds []*Cmd
	// Set the operation record of the current command set to persist the saved file. If not set, the history operation record will be cleared every time the command set is switched.
	History string
	// Set the pre-detection function for all commands executed in the current command set
	PreCheck func(ctx Context) error
	// Set the prompt string when switching to the command set(custom word color)
	Prompt []*Word
	// Set the notification function when switching to the command set, args is the parameter passed by SwitchCommandSet.
	OnChange func(ctx Context, args []interface{})
}

// comman set name
func WithName(v string) CommandSetOption {
	return func(cc *CommandSetOptions) CommandSetOption {
		previous := cc.Name
		cc.Name = v
		return WithName(previous)
	}
}

// command set commands
func WithCmds(v ...*Cmd) CommandSetOption {
	return func(cc *CommandSetOptions) CommandSetOption {
		previous := cc.Cmds
		cc.Cmds = v
		return WithCmds(previous...)
	}
}

// Set the operation record of the current command set to persist the saved file. If not set, the history operation record will be cleared every time the command set is switched.
func WithHistory(v string) CommandSetOption {
	return func(cc *CommandSetOptions) CommandSetOption {
		previous := cc.History
		cc.History = v
		return WithHistory(previous)
	}
}

// Set the pre-detection function for all commands executed in the current command set
func WithPreCheck(v func(ctx Context) error) CommandSetOption {
	return func(cc *CommandSetOptions) CommandSetOption {
		previous := cc.PreCheck
		cc.PreCheck = v
		return WithPreCheck(previous)
	}
}

// Set the prompt string when switching to the command set(custom word color)
func WithPrompt(v ...*Word) CommandSetOption {
	return func(cc *CommandSetOptions) CommandSetOption {
		previous := cc.Prompt
		cc.Prompt = v
		return WithPrompt(previous...)
	}
}

// Set the notification function when switching to the command set, args is the parameter passed by SwitchCommandSet.
func WithOnChange(v func(ctx Context, args []interface{})) CommandSetOption {
	return func(cc *CommandSetOptions) CommandSetOption {
		previous := cc.OnChange
		cc.OnChange = v
		return WithOnChange(previous)
	}
}

// SetOption modify options
func (cc *CommandSetOptions) SetOption(opt CommandSetOption) {
	_ = opt(cc)
}

// ApplyOption modify options
func (cc *CommandSetOptions) ApplyOption(opts ...CommandSetOption) {
	for _, opt := range opts {
		_ = opt(cc)
	}
}

// GetSetOption modify and get last option
func (cc *CommandSetOptions) GetSetOption(opt CommandSetOption) CommandSetOption {
	return opt(cc)
}

// CommandSetOption option define
type CommandSetOption func(cc *CommandSetOptions) CommandSetOption

// NewCommandSetOptions create options instance.
func NewCommandSetOptions(opts ...CommandSetOption) *CommandSetOptions {
	cc := newDefaultCommandSetOptions()
	for _, opt := range opts {
		_ = opt(cc)
	}
	if watchDogCommandSetOptions != nil {
		watchDogCommandSetOptions(cc)
	}
	return cc
}

// InstallCommandSetOptionsWatchDog install watch dog
func InstallCommandSetOptionsWatchDog(dog func(cc *CommandSetOptions)) {
	watchDogCommandSetOptions = dog
}

var watchDogCommandSetOptions func(cc *CommandSetOptions)

// newDefaultCommandSetOptions new option with default value
func newDefaultCommandSetOptions() *CommandSetOptions {
	cc := &CommandSetOptions{
		Name:     "",
		Cmds:     nil,
		History:  "",
		PreCheck: nil,
		Prompt:   nil,
		OnChange: func(ctx Context, args []interface{}) {
		},
	}
	return cc
}
