// Code generated by "gogen import"; DO NOT EDIT.
// Exec: "gogen import ./completion -t Suggest -t CompletionManager -t Filter -o gen_pkg_completion.go"
// Version: 0.0.2

package promptx

import completion "github.com/aggronmagi/promptx/completion"

// Suggest is printed when completing.
type Suggest = completion.Suggest

// CompletionManager manages which suggestion is now selected.
type CompletionManager = completion.CompletionManager

// Filter is the type to filter the prompt.Suggestion array.
type Filter = completion.Filter
