// Code generated by "gogen option"; DO NOT EDIT.
// Exec: "gogen option -n InputOption -f -o gen_options_input.go"
// Version: 0.0.4

package promptx

var _ = promptxInputOptions()

// InputOptions promptx options
// generate by https://github.com/aggronmagi/gogen/
type InputOptions struct {
	Tip         string
	TipColor    Color
	TipBG       Color
	Prefix      string
	PrefixColor Color
	PrefixBG    Color
	Valid       func(*Document) error
	ValidColor  Color
	ValidBG     Color
	OnFinish    func(input string, eof error)
	Finish      Key
	Cancel      Key
	// result display
	ResultText   InputFinishTextFunc
	ResultColor  Color
	ResultBG     Color
	Default      string
	DefaultColor Color
	DefaultBG    Color
}

func WithInputOptionTip(v string) InputOption {
	return func(cc *InputOptions) InputOption {
		previous := cc.Tip
		cc.Tip = v
		return WithInputOptionTip(previous)
	}
}

func WithInputOptionTipColor(v Color) InputOption {
	return func(cc *InputOptions) InputOption {
		previous := cc.TipColor
		cc.TipColor = v
		return WithInputOptionTipColor(previous)
	}
}

func WithInputOptionTipBG(v Color) InputOption {
	return func(cc *InputOptions) InputOption {
		previous := cc.TipBG
		cc.TipBG = v
		return WithInputOptionTipBG(previous)
	}
}

func WithInputOptionPrefix(v string) InputOption {
	return func(cc *InputOptions) InputOption {
		previous := cc.Prefix
		cc.Prefix = v
		return WithInputOptionPrefix(previous)
	}
}

func WithInputOptionPrefixColor(v Color) InputOption {
	return func(cc *InputOptions) InputOption {
		previous := cc.PrefixColor
		cc.PrefixColor = v
		return WithInputOptionPrefixColor(previous)
	}
}

func WithInputOptionPrefixBG(v Color) InputOption {
	return func(cc *InputOptions) InputOption {
		previous := cc.PrefixBG
		cc.PrefixBG = v
		return WithInputOptionPrefixBG(previous)
	}
}

func WithInputOptionValid(v func(*Document) error) InputOption {
	return func(cc *InputOptions) InputOption {
		previous := cc.Valid
		cc.Valid = v
		return WithInputOptionValid(previous)
	}
}

func WithInputOptionValidColor(v Color) InputOption {
	return func(cc *InputOptions) InputOption {
		previous := cc.ValidColor
		cc.ValidColor = v
		return WithInputOptionValidColor(previous)
	}
}

func WithInputOptionValidBG(v Color) InputOption {
	return func(cc *InputOptions) InputOption {
		previous := cc.ValidBG
		cc.ValidBG = v
		return WithInputOptionValidBG(previous)
	}
}

func WithInputOptionOnFinish(v func(input string, eof error)) InputOption {
	return func(cc *InputOptions) InputOption {
		previous := cc.OnFinish
		cc.OnFinish = v
		return WithInputOptionOnFinish(previous)
	}
}

func WithInputOptionFinish(v Key) InputOption {
	return func(cc *InputOptions) InputOption {
		previous := cc.Finish
		cc.Finish = v
		return WithInputOptionFinish(previous)
	}
}

func WithInputOptionCancel(v Key) InputOption {
	return func(cc *InputOptions) InputOption {
		previous := cc.Cancel
		cc.Cancel = v
		return WithInputOptionCancel(previous)
	}
}

// result display
func WithInputOptionResultText(v InputFinishTextFunc) InputOption {
	return func(cc *InputOptions) InputOption {
		previous := cc.ResultText
		cc.ResultText = v
		return WithInputOptionResultText(previous)
	}
}

func WithInputOptionResultColor(v Color) InputOption {
	return func(cc *InputOptions) InputOption {
		previous := cc.ResultColor
		cc.ResultColor = v
		return WithInputOptionResultColor(previous)
	}
}

func WithInputOptionResultBG(v Color) InputOption {
	return func(cc *InputOptions) InputOption {
		previous := cc.ResultBG
		cc.ResultBG = v
		return WithInputOptionResultBG(previous)
	}
}

func WithInputOptionDefault(v string) InputOption {
	return func(cc *InputOptions) InputOption {
		previous := cc.Default
		cc.Default = v
		return WithInputOptionDefault(previous)
	}
}

func WithInputOptionDefaultColor(v Color) InputOption {
	return func(cc *InputOptions) InputOption {
		previous := cc.DefaultColor
		cc.DefaultColor = v
		return WithInputOptionDefaultColor(previous)
	}
}

func WithInputOptionDefaultBG(v Color) InputOption {
	return func(cc *InputOptions) InputOption {
		previous := cc.DefaultBG
		cc.DefaultBG = v
		return WithInputOptionDefaultBG(previous)
	}
}

// SetOption modify options
func (cc *InputOptions) SetOption(opt InputOption) {
	_ = opt(cc)
}

// ApplyOption modify options
func (cc *InputOptions) ApplyOption(opts ...InputOption) {
	for _, opt := range opts {
		_ = opt(cc)
	}
}

// GetSetOption modify and get last option
func (cc *InputOptions) GetSetOption(opt InputOption) InputOption {
	return opt(cc)
}

// InputOption option define
type InputOption func(cc *InputOptions) InputOption

// NewInputOptions create options instance.
func NewInputOptions(opts ...InputOption) *InputOptions {
	cc := newDefaultInputOptions()
	for _, opt := range opts {
		_ = opt(cc)
	}
	if watchDogInputOptions != nil {
		watchDogInputOptions(cc)
	}
	return cc
}

// InstallInputOptionsWatchDog install watch dog
func InstallInputOptionsWatchDog(dog func(cc *InputOptions)) {
	watchDogInputOptions = dog
}

var watchDogInputOptions func(cc *InputOptions)

// newDefaultInputOptions new option with default value
func newDefaultInputOptions() *InputOptions {
	cc := &InputOptions{
		Tip:          "",
		TipColor:     Yellow,
		TipBG:        DefaultColor,
		Prefix:       ">> ",
		PrefixColor:  Green,
		PrefixBG:     DefaultColor,
		Valid:        nil,
		ValidColor:   Red,
		ValidBG:      DefaultColor,
		OnFinish:     nil,
		Finish:       Enter,
		Cancel:       ControlC,
		ResultText:   defaultInputFinishText,
		ResultColor:  Blue,
		ResultBG:     DefaultColor,
		Default:      "",
		DefaultColor: Brown,
		DefaultBG:    DefaultColor,
	}
	return cc
}
