// Code generated by "gogen import"; DO NOT EDIT.
// Exec: "gogen import ./input -t WinSize -t ConsoleParser -t Key -t ASCIICode -o gen_pkg_input.go"
// Version: 0.0.2

package promptx

import input "github.com/aggronmagi/promptx/input"

// WinSize represents the width and height of terminal.
type WinSize = input.WinSize

// ConsoleParser is an interface to abstract input layer.
type ConsoleParser = input.ConsoleParser

// Key is the type express the key inserted from user.
type Key = input.Key

const (
	// Matches any key.
	Any            = input.Any
	BackTab        = input.BackTab
	Backspace      = input.Backspace
	BracketedPaste = input.BracketedPaste
	// Special
	CPRResponse        = input.CPRResponse
	ControlA           = input.ControlA
	ControlB           = input.ControlB
	ControlBackslash   = input.ControlBackslash
	ControlC           = input.ControlC
	ControlCircumflex  = input.ControlCircumflex
	ControlD           = input.ControlD
	ControlDelete      = input.ControlDelete
	ControlDown        = input.ControlDown
	ControlE           = input.ControlE
	ControlF           = input.ControlF
	ControlG           = input.ControlG
	ControlH           = input.ControlH
	ControlK           = input.ControlK
	ControlL           = input.ControlL
	ControlLeft        = input.ControlLeft
	ControlN           = input.ControlN
	ControlO           = input.ControlO
	ControlP           = input.ControlP
	ControlQ           = input.ControlQ
	ControlR           = input.ControlR
	ControlRight       = input.ControlRight
	ControlS           = input.ControlS
	ControlSpace       = input.ControlSpace
	ControlSquareClose = input.ControlSquareClose
	ControlT           = input.ControlT
	ControlU           = input.ControlU
	ControlUnderscore  = input.ControlUnderscore
	ControlUp          = input.ControlUp
	ControlV           = input.ControlV
	ControlW           = input.ControlW
	ControlX           = input.ControlX
	ControlY           = input.ControlY
	ControlZ           = input.ControlZ
	Delete             = input.Delete
	Down               = input.Down
	End                = input.End
	Enter              = input.Enter
	Escape             = input.Escape
	F1                 = input.F1
	F10                = input.F10
	F11                = input.F11
	F12                = input.F12
	F13                = input.F13
	F14                = input.F14
	F15                = input.F15
	F16                = input.F16
	F17                = input.F17
	F18                = input.F18
	F19                = input.F19
	F2                 = input.F2
	F20                = input.F20
	F21                = input.F21
	F22                = input.F22
	F23                = input.F23
	F24                = input.F24
	F3                 = input.F3
	F4                 = input.F4
	F5                 = input.F5
	F6                 = input.F6
	F7                 = input.F7
	F8                 = input.F8
	F9                 = input.F9
	Home               = input.Home
	// Key which is ignored. (The key binding for this key should not do anything.)
	Ignore = input.Ignore
	Insert = input.Insert
	Left   = input.Left
	// Meta[Alt] + [a-f]
	MetaA = input.MetaA
	MetaB = input.MetaB
	MetaC = input.MetaC
	MetaD = input.MetaD
	MetaE = input.MetaE
	MetaF = input.MetaF
	MetaG = input.MetaG
	MetaH = input.MetaH
	MetaI = input.MetaI
	MetaJ = input.MetaJ
	MetaK = input.MetaK
	MetaL = input.MetaL
	MetaM = input.MetaM
	MetaN = input.MetaN
	MetaO = input.MetaO
	MetaP = input.MetaP
	MetaQ = input.MetaQ
	MetaR = input.MetaR
	MetaS = input.MetaS
	// Meta[Alt] + Shift [a-z]
	// Meta[Alt] + [A-Z]
	MetaShiftA = input.MetaShiftA
	MetaShiftB = input.MetaShiftB
	MetaShiftC = input.MetaShiftC
	MetaShiftD = input.MetaShiftD
	MetaShiftE = input.MetaShiftE
	MetaShiftF = input.MetaShiftF
	MetaShiftG = input.MetaShiftG
	MetaShiftH = input.MetaShiftH
	MetaShiftI = input.MetaShiftI
	MetaShiftJ = input.MetaShiftJ
	MetaShiftK = input.MetaShiftK
	MetaShiftL = input.MetaShiftL
	MetaShiftM = input.MetaShiftM
	MetaShiftN = input.MetaShiftN
	MetaShiftO = input.MetaShiftO
	MetaShiftP = input.MetaShiftP
	MetaShiftQ = input.MetaShiftQ
	MetaShiftR = input.MetaShiftR
	MetaShiftS = input.MetaShiftS
	MetaShiftT = input.MetaShiftT
	MetaShiftU = input.MetaShiftU
	MetaShiftV = input.MetaShiftV
	MetaShiftW = input.MetaShiftW
	MetaShiftX = input.MetaShiftX
	MetaShiftY = input.MetaShiftY
	MetaShiftZ = input.MetaShiftZ
	MetaT      = input.MetaT
	MetaU      = input.MetaU
	MetaV      = input.MetaV
	MetaW      = input.MetaW
	MetaX      = input.MetaX
	MetaY      = input.MetaY
	MetaZ      = input.MetaZ
	// Key is not defined
	NotDefined  = input.NotDefined
	PageDown    = input.PageDown
	PageUp      = input.PageUp
	Right       = input.Right
	ShiftDelete = input.ShiftDelete
	ShiftDown   = input.ShiftDown
	ShiftLeft   = input.ShiftLeft
	ShiftRight  = input.ShiftRight
	ShiftUp     = input.ShiftUp
	// Aliases.
	Tab               = input.Tab
	Up                = input.Up
	Vt100MouseEvent   = input.Vt100MouseEvent
	WindowsMouseEvent = input.WindowsMouseEvent
)

// ASCIICode is the type contains Key and it's ascii byte array.
type ASCIICode = input.ASCIICode
