// Code generated by "gogen import"; DO NOT EDIT.
// Exec: "gogen import ./buffer -t Buffer -t Document -o gen_pkg_buffer.go"
// Version: 0.0.2

package promptx

import buffer "github.com/aggronmagi/promptx/buffer"

// Buffer emulates the console buffer.
type Buffer = buffer.Buffer

// Document has text displayed in terminal and cursor position.
type Document = buffer.Document
