// Code generated by "gogen option"; DO NOT EDIT.
// Exec: "gogen option -n CommonOption -f -o gen_options_common.go"
// Version: 0.0.4

package promptx

var _ = promptxCommonOptions()

// CommonOptions promptx options
// generate by https://github.com/aggronmagi/gogen/
type CommonOptions struct {
	Tip         string
	TipColor    Color
	TipBG       Color
	Prefix      string
	PrefixColor Color
	PrefixBG    Color
	// check input valid
	Valid      func(status int, in *Document) error
	ValidColor Color
	ValidBG    Color
	// exec input command
	Exec     func(ctx Context, command string)
	Finish   Key
	Cancel   Key
	Complete []CompleteOption
	// if command slice size > 0. it will ignore Exec and Valid options
	Cmds []*Cmd
	// alway check input command
	AlwaysCheck bool
	// history file
	History string
	// CommandPreCheck check before exec Cmd. only use for promptx.Cmd.
	PreCheck func(ctx Context) error
}

func WithCommonOptionTip(v string) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.Tip
		cc.Tip = v
		return WithCommonOptionTip(previous)
	}
}

func WithCommonOptionTipColor(v Color) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.TipColor
		cc.TipColor = v
		return WithCommonOptionTipColor(previous)
	}
}

func WithCommonOptionTipBG(v Color) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.TipBG
		cc.TipBG = v
		return WithCommonOptionTipBG(previous)
	}
}

func WithCommonOptionPrefix(v string) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.Prefix
		cc.Prefix = v
		return WithCommonOptionPrefix(previous)
	}
}

func WithCommonOptionPrefixColor(v Color) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.PrefixColor
		cc.PrefixColor = v
		return WithCommonOptionPrefixColor(previous)
	}
}

func WithCommonOptionPrefixBG(v Color) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.PrefixBG
		cc.PrefixBG = v
		return WithCommonOptionPrefixBG(previous)
	}
}

// check input valid
func WithCommonOptionValid(v func(status int, in *Document) error) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.Valid
		cc.Valid = v
		return WithCommonOptionValid(previous)
	}
}

func WithCommonOptionValidColor(v Color) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.ValidColor
		cc.ValidColor = v
		return WithCommonOptionValidColor(previous)
	}
}

func WithCommonOptionValidBG(v Color) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.ValidBG
		cc.ValidBG = v
		return WithCommonOptionValidBG(previous)
	}
}

// exec input command
func WithCommonOptionExec(v func(ctx Context, command string)) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.Exec
		cc.Exec = v
		return WithCommonOptionExec(previous)
	}
}

func WithCommonOptionFinish(v Key) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.Finish
		cc.Finish = v
		return WithCommonOptionFinish(previous)
	}
}

func WithCommonOptionCancel(v Key) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.Cancel
		cc.Cancel = v
		return WithCommonOptionCancel(previous)
	}
}

func WithCommonOptionComplete(v ...CompleteOption) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.Complete
		cc.Complete = v
		return WithCommonOptionComplete(previous...)
	}
}

// if command slice size > 0. it will ignore Exec and Valid options
func WithCommonOptionCmds(v ...*Cmd) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.Cmds
		cc.Cmds = v
		return WithCommonOptionCmds(previous...)
	}
}

// alway check input command
func WithCommonOptionAlwaysCheck(v bool) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.AlwaysCheck
		cc.AlwaysCheck = v
		return WithCommonOptionAlwaysCheck(previous)
	}
}

// history file
func WithCommonOptionHistory(v string) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.History
		cc.History = v
		return WithCommonOptionHistory(previous)
	}
}

// CommandPreCheck check before exec Cmd. only use for promptx.Cmd.
func WithCommonOptionPreCheck(v func(ctx Context) error) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.PreCheck
		cc.PreCheck = v
		return WithCommonOptionPreCheck(previous)
	}
}

// SetOption modify options
func (cc *CommonOptions) SetOption(opt CommonOption) {
	_ = opt(cc)
}

// ApplyOption modify options
func (cc *CommonOptions) ApplyOption(opts ...CommonOption) {
	for _, opt := range opts {
		_ = opt(cc)
	}
}

// GetSetOption modify and get last option
func (cc *CommonOptions) GetSetOption(opt CommonOption) CommonOption {
	return opt(cc)
}

// CommonOption option define
type CommonOption func(cc *CommonOptions) CommonOption

// NewCommonOptions create options instance.
func NewCommonOptions(opts ...CommonOption) *CommonOptions {
	cc := newDefaultCommonOptions()
	for _, opt := range opts {
		_ = opt(cc)
	}
	if watchDogCommonOptions != nil {
		watchDogCommonOptions(cc)
	}
	return cc
}

// InstallCommonOptionsWatchDog install watch dog
func InstallCommonOptionsWatchDog(dog func(cc *CommonOptions)) {
	watchDogCommonOptions = dog
}

var watchDogCommonOptions func(cc *CommonOptions)

// newDefaultCommonOptions new option with default value
func newDefaultCommonOptions() *CommonOptions {
	cc := &CommonOptions{
		Tip:         "",
		TipColor:    Yellow,
		TipBG:       DefaultColor,
		Prefix:      ">>> ",
		PrefixColor: Green,
		PrefixBG:    DefaultColor,
		Valid:       nil,
		ValidColor:  Red,
		ValidBG:     DefaultColor,
		Exec:        nil,
		Finish:      Enter,
		Cancel:      ControlC,
		Complete:    nil,
		Cmds:        nil,
		AlwaysCheck: false,
		History:     "",
		PreCheck:    nil,
	}
	return cc
}
