// Code generated by "gogen option"; DO NOT EDIT.
// Exec: "gogen option -n SelectOption -f -o gen_options_select.go"
// Version: 0.0.4

package promptx

var _ = promptxSelectOptions()

// SelectOptions promptx options
// generate by https://github.com/aggronmagi/gogen/
type SelectOptions struct {
	Options         []*Suggest
	Rows            int
	OnFinish        func(sels []int)
	Multi           bool
	Finish          Key
	Cancel          Key
	Tip             string
	TipColor        Color
	TipBG           Color
	ShowHelp        bool
	Help            SelHelpTextFunc
	HelpColor       Color
	HelpBG          Color
	Valid           func(sels []int) error
	ValidColor      Color
	ValidBG         Color
	SuggestColor    Color
	SuggestBG       Color
	SelSuggestColor Color
	SelSuggestBG    Color
	DescColor       Color
	DescBG          Color
	SelDescColor    Color
	SelDescBG       Color
	BarColor        Color
	BarBG           Color
	FinishText      SelFinishTextFunc
	ShowItem        bool
	ResultColor     Color
	ResultBG        Color
	Defaults        []int
}

func WithSelectOptionOptions(v ...*Suggest) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.Options
		cc.Options = v
		return WithSelectOptionOptions(previous...)
	}
}

func WithSelectOptionRows(v int) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.Rows
		cc.Rows = v
		return WithSelectOptionRows(previous)
	}
}

func WithSelectOptionOnFinish(v func(sels []int)) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.OnFinish
		cc.OnFinish = v
		return WithSelectOptionOnFinish(previous)
	}
}

func WithSelectOptionMulti(v bool) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.Multi
		cc.Multi = v
		return WithSelectOptionMulti(previous)
	}
}

func WithSelectOptionFinish(v Key) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.Finish
		cc.Finish = v
		return WithSelectOptionFinish(previous)
	}
}

func WithSelectOptionCancel(v Key) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.Cancel
		cc.Cancel = v
		return WithSelectOptionCancel(previous)
	}
}

func WithSelectOptionTip(v string) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.Tip
		cc.Tip = v
		return WithSelectOptionTip(previous)
	}
}

func WithSelectOptionTipColor(v Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.TipColor
		cc.TipColor = v
		return WithSelectOptionTipColor(previous)
	}
}

func WithSelectOptionTipBG(v Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.TipBG
		cc.TipBG = v
		return WithSelectOptionTipBG(previous)
	}
}

func WithSelectOptionShowHelp(v bool) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.ShowHelp
		cc.ShowHelp = v
		return WithSelectOptionShowHelp(previous)
	}
}

func WithSelectOptionHelp(v SelHelpTextFunc) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.Help
		cc.Help = v
		return WithSelectOptionHelp(previous)
	}
}

func WithSelectOptionHelpColor(v Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.HelpColor
		cc.HelpColor = v
		return WithSelectOptionHelpColor(previous)
	}
}

func WithSelectOptionHelpBG(v Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.HelpBG
		cc.HelpBG = v
		return WithSelectOptionHelpBG(previous)
	}
}

func WithSelectOptionValid(v func(sels []int) error) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.Valid
		cc.Valid = v
		return WithSelectOptionValid(previous)
	}
}

func WithSelectOptionValidColor(v Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.ValidColor
		cc.ValidColor = v
		return WithSelectOptionValidColor(previous)
	}
}

func WithSelectOptionValidBG(v Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.ValidBG
		cc.ValidBG = v
		return WithSelectOptionValidBG(previous)
	}
}

func WithSelectOptionSuggestColor(v Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.SuggestColor
		cc.SuggestColor = v
		return WithSelectOptionSuggestColor(previous)
	}
}

func WithSelectOptionSuggestBG(v Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.SuggestBG
		cc.SuggestBG = v
		return WithSelectOptionSuggestBG(previous)
	}
}

func WithSelectOptionSelSuggestColor(v Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.SelSuggestColor
		cc.SelSuggestColor = v
		return WithSelectOptionSelSuggestColor(previous)
	}
}

func WithSelectOptionSelSuggestBG(v Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.SelSuggestBG
		cc.SelSuggestBG = v
		return WithSelectOptionSelSuggestBG(previous)
	}
}

func WithSelectOptionDescColor(v Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.DescColor
		cc.DescColor = v
		return WithSelectOptionDescColor(previous)
	}
}

func WithSelectOptionDescBG(v Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.DescBG
		cc.DescBG = v
		return WithSelectOptionDescBG(previous)
	}
}

func WithSelectOptionSelDescColor(v Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.SelDescColor
		cc.SelDescColor = v
		return WithSelectOptionSelDescColor(previous)
	}
}

func WithSelectOptionSelDescBG(v Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.SelDescBG
		cc.SelDescBG = v
		return WithSelectOptionSelDescBG(previous)
	}
}

func WithSelectOptionBarColor(v Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.BarColor
		cc.BarColor = v
		return WithSelectOptionBarColor(previous)
	}
}

func WithSelectOptionBarBG(v Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.BarBG
		cc.BarBG = v
		return WithSelectOptionBarBG(previous)
	}
}

func WithSelectOptionFinishText(v SelFinishTextFunc) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.FinishText
		cc.FinishText = v
		return WithSelectOptionFinishText(previous)
	}
}

func WithSelectOptionShowItem(v bool) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.ShowItem
		cc.ShowItem = v
		return WithSelectOptionShowItem(previous)
	}
}

func WithSelectOptionResultColor(v Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.ResultColor
		cc.ResultColor = v
		return WithSelectOptionResultColor(previous)
	}
}

func WithSelectOptionResultBG(v Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.ResultBG
		cc.ResultBG = v
		return WithSelectOptionResultBG(previous)
	}
}

func WithSelectOptionDefaults(v ...int) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.Defaults
		cc.Defaults = v
		return WithSelectOptionDefaults(previous...)
	}
}

// SetOption modify options
func (cc *SelectOptions) SetOption(opt SelectOption) {
	_ = opt(cc)
}

// ApplyOption modify options
func (cc *SelectOptions) ApplyOption(opts ...SelectOption) {
	for _, opt := range opts {
		_ = opt(cc)
	}
}

// GetSetOption modify and get last option
func (cc *SelectOptions) GetSetOption(opt SelectOption) SelectOption {
	return opt(cc)
}

// SelectOption option define
type SelectOption func(cc *SelectOptions) SelectOption

// NewSelectOptions create options instance.
func NewSelectOptions(opts ...SelectOption) *SelectOptions {
	cc := newDefaultSelectOptions()
	for _, opt := range opts {
		_ = opt(cc)
	}
	if watchDogSelectOptions != nil {
		watchDogSelectOptions(cc)
	}
	return cc
}

// InstallSelectOptionsWatchDog install watch dog
func InstallSelectOptionsWatchDog(dog func(cc *SelectOptions)) {
	watchDogSelectOptions = dog
}

var watchDogSelectOptions func(cc *SelectOptions)

// newDefaultSelectOptions new option with default value
func newDefaultSelectOptions() *SelectOptions {
	cc := &SelectOptions{
		Options:         nil,
		Rows:            5,
		OnFinish:        nil,
		Multi:           false,
		Finish:          Enter,
		Cancel:          ControlC,
		Tip:             "",
		TipColor:        Yellow,
		TipBG:           DefaultColor,
		ShowHelp:        false,
		Help:            defaultSelHelpText,
		HelpColor:       DefaultColor,
		HelpBG:          DefaultColor,
		Valid:           nil,
		ValidColor:      Red,
		ValidBG:         DefaultColor,
		SuggestColor:    White,
		SuggestBG:       Cyan,
		SelSuggestColor: Black,
		SelSuggestBG:    Turquoise,
		DescColor:       Black,
		DescBG:          Turquoise,
		SelDescColor:    White,
		SelDescBG:       Cyan,
		BarColor:        DarkGray,
		BarBG:           Cyan,
		FinishText:      defaultSelFinishText,
		ShowItem:        true,
		ResultColor:     Blue,
		ResultBG:        DefaultColor,
		Defaults:        nil,
	}
	return cc
}
