// Code generated by "gogen option"; DO NOT EDIT.
// Exec: "gogen option -n CompleteOption -f -o gen_options_complete.go"
// Version: 0.0.4

package blocks

import (
	"github.com/aggronmagi/promptx/v2/output"
)

var _ = promptxCompleteOptions()

// CompleteOptions promptx options
// generate by https://github.com/aggronmagi/gogen/
type CompleteOptions struct {
	SuggestionTextColor          output.Color
	SuggestionBGColor            output.Color
	SelectedSuggestionTextColor  output.Color
	SelectedSuggestionBGColor    output.Color
	DescriptionTextColor         output.Color
	DescriptionBGColor           output.Color
	SelectedDescriptionTextColor output.Color
	SelectedDescriptionBGColor   output.Color
	ScrollbarThumbColor          output.Color
	ScrollbarBGColor             output.Color
	Completer                    Completer
	CompleteMax                  int
	CompletionFillSpace          bool
	WordSeparator                string
}

func WithCompleteOptionSuggestionTextColor(v output.Color) CompleteOption {
	return func(cc *CompleteOptions) CompleteOption {
		previous := cc.SuggestionTextColor
		cc.SuggestionTextColor = v
		return WithCompleteOptionSuggestionTextColor(previous)
	}
}

func WithCompleteOptionSuggestionBGColor(v output.Color) CompleteOption {
	return func(cc *CompleteOptions) CompleteOption {
		previous := cc.SuggestionBGColor
		cc.SuggestionBGColor = v
		return WithCompleteOptionSuggestionBGColor(previous)
	}
}

func WithCompleteOptionSelectedSuggestionTextColor(v output.Color) CompleteOption {
	return func(cc *CompleteOptions) CompleteOption {
		previous := cc.SelectedSuggestionTextColor
		cc.SelectedSuggestionTextColor = v
		return WithCompleteOptionSelectedSuggestionTextColor(previous)
	}
}

func WithCompleteOptionSelectedSuggestionBGColor(v output.Color) CompleteOption {
	return func(cc *CompleteOptions) CompleteOption {
		previous := cc.SelectedSuggestionBGColor
		cc.SelectedSuggestionBGColor = v
		return WithCompleteOptionSelectedSuggestionBGColor(previous)
	}
}

func WithCompleteOptionDescriptionTextColor(v output.Color) CompleteOption {
	return func(cc *CompleteOptions) CompleteOption {
		previous := cc.DescriptionTextColor
		cc.DescriptionTextColor = v
		return WithCompleteOptionDescriptionTextColor(previous)
	}
}

func WithCompleteOptionDescriptionBGColor(v output.Color) CompleteOption {
	return func(cc *CompleteOptions) CompleteOption {
		previous := cc.DescriptionBGColor
		cc.DescriptionBGColor = v
		return WithCompleteOptionDescriptionBGColor(previous)
	}
}

func WithCompleteOptionSelectedDescriptionTextColor(v output.Color) CompleteOption {
	return func(cc *CompleteOptions) CompleteOption {
		previous := cc.SelectedDescriptionTextColor
		cc.SelectedDescriptionTextColor = v
		return WithCompleteOptionSelectedDescriptionTextColor(previous)
	}
}

func WithCompleteOptionSelectedDescriptionBGColor(v output.Color) CompleteOption {
	return func(cc *CompleteOptions) CompleteOption {
		previous := cc.SelectedDescriptionBGColor
		cc.SelectedDescriptionBGColor = v
		return WithCompleteOptionSelectedDescriptionBGColor(previous)
	}
}

func WithCompleteOptionScrollbarThumbColor(v output.Color) CompleteOption {
	return func(cc *CompleteOptions) CompleteOption {
		previous := cc.ScrollbarThumbColor
		cc.ScrollbarThumbColor = v
		return WithCompleteOptionScrollbarThumbColor(previous)
	}
}

func WithCompleteOptionScrollbarBGColor(v output.Color) CompleteOption {
	return func(cc *CompleteOptions) CompleteOption {
		previous := cc.ScrollbarBGColor
		cc.ScrollbarBGColor = v
		return WithCompleteOptionScrollbarBGColor(previous)
	}
}

func WithCompleteOptionCompleter(v Completer) CompleteOption {
	return func(cc *CompleteOptions) CompleteOption {
		previous := cc.Completer
		cc.Completer = v
		return WithCompleteOptionCompleter(previous)
	}
}

func WithCompleteOptionCompleteMax(v int) CompleteOption {
	return func(cc *CompleteOptions) CompleteOption {
		previous := cc.CompleteMax
		cc.CompleteMax = v
		return WithCompleteOptionCompleteMax(previous)
	}
}

func WithCompleteOptionCompletionFillSpace(v bool) CompleteOption {
	return func(cc *CompleteOptions) CompleteOption {
		previous := cc.CompletionFillSpace
		cc.CompletionFillSpace = v
		return WithCompleteOptionCompletionFillSpace(previous)
	}
}

func WithCompleteOptionWordSeparator(v string) CompleteOption {
	return func(cc *CompleteOptions) CompleteOption {
		previous := cc.WordSeparator
		cc.WordSeparator = v
		return WithCompleteOptionWordSeparator(previous)
	}
}

// SetOption modify options
func (cc *CompleteOptions) SetOption(opt CompleteOption) {
	_ = opt(cc)
}

// ApplyOption modify options
func (cc *CompleteOptions) ApplyOption(opts ...CompleteOption) {
	for _, opt := range opts {
		_ = opt(cc)
	}
}

// GetSetOption modify and get last option
func (cc *CompleteOptions) GetSetOption(opt CompleteOption) CompleteOption {
	return opt(cc)
}

// CompleteOption option define
type CompleteOption func(cc *CompleteOptions) CompleteOption

// NewCompleteOptions create options instance.
func NewCompleteOptions(opts ...CompleteOption) *CompleteOptions {
	cc := newDefaultCompleteOptions()
	for _, opt := range opts {
		_ = opt(cc)
	}
	if watchDogCompleteOptions != nil {
		watchDogCompleteOptions(cc)
	}
	return cc
}

// InstallCompleteOptionsWatchDog install watch dog
func InstallCompleteOptionsWatchDog(dog func(cc *CompleteOptions)) {
	watchDogCompleteOptions = dog
}

var watchDogCompleteOptions func(cc *CompleteOptions)

// newDefaultCompleteOptions new option with default value
func newDefaultCompleteOptions() *CompleteOptions {
	cc := &CompleteOptions{
		SuggestionTextColor:          output.White,
		SuggestionBGColor:            output.Cyan,
		SelectedSuggestionTextColor:  output.Black,
		SelectedSuggestionBGColor:    output.Turquoise,
		DescriptionTextColor:         output.Black,
		DescriptionBGColor:           output.Turquoise,
		SelectedDescriptionTextColor: output.White,
		SelectedDescriptionBGColor:   output.Cyan,
		ScrollbarThumbColor:          output.DarkGray,
		ScrollbarBGColor:             output.Cyan,
		Completer:                    nil,
		CompleteMax:                  5,
		CompletionFillSpace:          false,
		WordSeparator:                " ",
	}
	return cc
}
