// Code generated by "gogen option"; DO NOT EDIT.
// Exec: "gogen option -n CommonOption -f -o gen_options_common.go"
// Version: 0.0.4

package blocks

import (
	"github.com/aggronmagi/promptx/v2/buffer"
	"github.com/aggronmagi/promptx/v2/input"
	"github.com/aggronmagi/promptx/v2/output"
)

var _ = promptxCommonOptions()

// CommonOptions promptx options
// generate by https://github.com/aggronmagi/gogen/
type CommonOptions struct {
	Tip         string
	TipColor    output.Color
	TipBG       output.Color
	Prefix      string
	PrefixColor output.Color
	PrefixBG    output.Color
	// check input valid
	Valid      func(status int, in *buffer.Document) error
	ValidColor output.Color
	ValidBG    output.Color
	// exec input command
	Exec     func(ctx Context, command string)
	Finish   input.Key
	Cancel   input.Key
	Complete []CompleteOption
	// history file
	History string
	// maximum history size
	HistoryMaxSize int
	// ignore consecutive duplicates
	HistoryIgnoreDups bool
	// global deduplication
	HistoryDedup bool
	// record timestamps
	HistoryTimestamp bool
}

func WithCommonOptionTip(v string) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.Tip
		cc.Tip = v
		return WithCommonOptionTip(previous)
	}
}

func WithCommonOptionTipColor(v output.Color) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.TipColor
		cc.TipColor = v
		return WithCommonOptionTipColor(previous)
	}
}

func WithCommonOptionTipBG(v output.Color) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.TipBG
		cc.TipBG = v
		return WithCommonOptionTipBG(previous)
	}
}

func WithCommonOptionPrefix(v string) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.Prefix
		cc.Prefix = v
		return WithCommonOptionPrefix(previous)
	}
}

func WithCommonOptionPrefixColor(v output.Color) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.PrefixColor
		cc.PrefixColor = v
		return WithCommonOptionPrefixColor(previous)
	}
}

func WithCommonOptionPrefixBG(v output.Color) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.PrefixBG
		cc.PrefixBG = v
		return WithCommonOptionPrefixBG(previous)
	}
}

// check input valid
func WithCommonOptionValid(v func(status int, in *buffer.Document) error) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.Valid
		cc.Valid = v
		return WithCommonOptionValid(previous)
	}
}

func WithCommonOptionValidColor(v output.Color) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.ValidColor
		cc.ValidColor = v
		return WithCommonOptionValidColor(previous)
	}
}

func WithCommonOptionValidBG(v output.Color) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.ValidBG
		cc.ValidBG = v
		return WithCommonOptionValidBG(previous)
	}
}

// exec input command
func WithCommonOptionExec(v func(ctx Context, command string)) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.Exec
		cc.Exec = v
		return WithCommonOptionExec(previous)
	}
}

func WithCommonOptionFinish(v input.Key) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.Finish
		cc.Finish = v
		return WithCommonOptionFinish(previous)
	}
}

func WithCommonOptionCancel(v input.Key) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.Cancel
		cc.Cancel = v
		return WithCommonOptionCancel(previous)
	}
}

func WithCommonOptionComplete(v ...CompleteOption) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.Complete
		cc.Complete = v
		return WithCommonOptionComplete(previous...)
	}
}

// history file
func WithCommonOptionHistory(v string) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.History
		cc.History = v
		return WithCommonOptionHistory(previous)
	}
}

// maximum history size
func WithCommonOptionHistoryMaxSize(v int) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.HistoryMaxSize
		cc.HistoryMaxSize = v
		return WithCommonOptionHistoryMaxSize(previous)
	}
}

// ignore consecutive duplicates
func WithCommonOptionHistoryIgnoreDups(v bool) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.HistoryIgnoreDups
		cc.HistoryIgnoreDups = v
		return WithCommonOptionHistoryIgnoreDups(previous)
	}
}

// global deduplication
func WithCommonOptionHistoryDedup(v bool) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.HistoryDedup
		cc.HistoryDedup = v
		return WithCommonOptionHistoryDedup(previous)
	}
}

// record timestamps
func WithCommonOptionHistoryTimestamp(v bool) CommonOption {
	return func(cc *CommonOptions) CommonOption {
		previous := cc.HistoryTimestamp
		cc.HistoryTimestamp = v
		return WithCommonOptionHistoryTimestamp(previous)
	}
}

// SetOption modify options
func (cc *CommonOptions) SetOption(opt CommonOption) {
	_ = opt(cc)
}

// ApplyOption modify options
func (cc *CommonOptions) ApplyOption(opts ...CommonOption) {
	for _, opt := range opts {
		_ = opt(cc)
	}
}

// GetSetOption modify and get last option
func (cc *CommonOptions) GetSetOption(opt CommonOption) CommonOption {
	return opt(cc)
}

// CommonOption option define
type CommonOption func(cc *CommonOptions) CommonOption

// NewCommonOptions create options instance.
func NewCommonOptions(opts ...CommonOption) *CommonOptions {
	cc := newDefaultCommonOptions()
	for _, opt := range opts {
		_ = opt(cc)
	}
	if watchDogCommonOptions != nil {
		watchDogCommonOptions(cc)
	}
	return cc
}

// InstallCommonOptionsWatchDog install watch dog
func InstallCommonOptionsWatchDog(dog func(cc *CommonOptions)) {
	watchDogCommonOptions = dog
}

var watchDogCommonOptions func(cc *CommonOptions)

// newDefaultCommonOptions new option with default value
func newDefaultCommonOptions() *CommonOptions {
	cc := &CommonOptions{
		Tip:               "",
		TipColor:          output.Yellow,
		TipBG:             output.DefaultColor,
		Prefix:            ">>> ",
		PrefixColor:       output.Green,
		PrefixBG:          output.DefaultColor,
		Valid:             nil,
		ValidColor:        output.Red,
		ValidBG:           output.DefaultColor,
		Exec:              nil,
		Finish:            input.Enter,
		Cancel:            input.ControlC,
		Complete:          nil,
		History:           "",
		HistoryMaxSize:    10000,
		HistoryIgnoreDups: true,
		HistoryDedup:      false,
		HistoryTimestamp:  false,
	}
	return cc
}
