// Code generated by "gogen option"; DO NOT EDIT.
// Exec: "gogen option -n BlocksOption -o gen_options_blocks.go"
// Version: 0.0.4

package blocks

import (
	"github.com/aggronmagi/promptx/v2/input"
	"github.com/aggronmagi/promptx/v2/output"
)

var _ = promptxBlocksOptions()

// PromptOptions promptx options
// generate by https://github.com/aggronmagi/gogen/
type BlocksOptions struct {
	// default global input options
	Inputs []InputOption
	// default global select options
	Selects []SelectOption
	// default common options. use to create default optins
	Common []CommonOption
	// default manager. if it is not nil, ignore Common.
	Manager BlocksManager
	// input
	Input input.ConsoleParser
	// output
	Output output.ConsoleWriter
	Stderr output.ConsoleWriter
	// Context
	Context Context
}

// default global input options
func WithInputs(v ...InputOption) BlocksOption {
	return func(cc *BlocksOptions) BlocksOption {
		previous := cc.Inputs
		cc.Inputs = v
		return WithInputs(previous...)
	}
}

// default global select options
func WithSelects(v ...SelectOption) BlocksOption {
	return func(cc *BlocksOptions) BlocksOption {
		previous := cc.Selects
		cc.Selects = v
		return WithSelects(previous...)
	}
}

// default common options. use to create default optins
func WithCommon(v ...CommonOption) BlocksOption {
	return func(cc *BlocksOptions) BlocksOption {
		previous := cc.Common
		cc.Common = v
		return WithCommon(previous...)
	}
}

// default manager. if it is not nil, ignore Common.
func WithManager(v BlocksManager) BlocksOption {
	return func(cc *BlocksOptions) BlocksOption {
		previous := cc.Manager
		cc.Manager = v
		return WithManager(previous)
	}
}

// input
func WithInput(v input.ConsoleParser) BlocksOption {
	return func(cc *BlocksOptions) BlocksOption {
		previous := cc.Input
		cc.Input = v
		return WithInput(previous)
	}
}

// output
func WithOutput(v output.ConsoleWriter) BlocksOption {
	return func(cc *BlocksOptions) BlocksOption {
		previous := cc.Output
		cc.Output = v
		return WithOutput(previous)
	}
}

func WithStderr(v output.ConsoleWriter) BlocksOption {
	return func(cc *BlocksOptions) BlocksOption {
		previous := cc.Stderr
		cc.Stderr = v
		return WithStderr(previous)
	}
}

// Context
func WithContext(v Context) BlocksOption {
	return func(cc *BlocksOptions) BlocksOption {
		previous := cc.Context
		cc.Context = v
		return WithContext(previous)
	}
}

// SetOption modify options
func (cc *BlocksOptions) SetOption(opt BlocksOption) {
	_ = opt(cc)
}

// ApplyOption modify options
func (cc *BlocksOptions) ApplyOption(opts ...BlocksOption) {
	for _, opt := range opts {
		_ = opt(cc)
	}
}

// GetSetOption modify and get last option
func (cc *BlocksOptions) GetSetOption(opt BlocksOption) BlocksOption {
	return opt(cc)
}

// BlocksOption option define
type BlocksOption func(cc *BlocksOptions) BlocksOption

// NewBlocksOptions create options instance.
func NewBlocksOptions(opts ...BlocksOption) *BlocksOptions {
	cc := newDefaultBlocksOptions()
	for _, opt := range opts {
		_ = opt(cc)
	}
	if watchDogBlocksOptions != nil {
		watchDogBlocksOptions(cc)
	}
	return cc
}

// InstallBlocksOptionsWatchDog install watch dog
func InstallBlocksOptionsWatchDog(dog func(cc *BlocksOptions)) {
	watchDogBlocksOptions = dog
}

var watchDogBlocksOptions func(cc *BlocksOptions)

// newDefaultBlocksOptions new option with default value
func newDefaultBlocksOptions() *BlocksOptions {
	cc := &BlocksOptions{
		Inputs:  nil,
		Selects: nil,
		Common:  nil,
		Manager: nil,
		Input:   input.NewStandardInputParser(),
		Output:  output.NewStandardOutputWriter(),
		Stderr:  output.NewStderrWriter(),
		Context: nil,
	}
	return cc
}
