// Code generated by "gogen option"; DO NOT EDIT.
// Exec: "gogen option -n SelectOption -f -o gen_options_select.go"
// Version: 0.0.4

package blocks

import (
	"github.com/aggronmagi/promptx/v2/completion"
	"github.com/aggronmagi/promptx/v2/input"
	"github.com/aggronmagi/promptx/v2/output"
)

var _ = promptxSelectOptions()

// SelectOptions promptx options
// generate by https://github.com/aggronmagi/gogen/
type SelectOptions struct {
	Options         []*completion.Suggest
	Rows            int
	OnFinish        func(sels []int)
	Multi           bool
	Finish          input.Key
	Cancel          input.Key
	Tip             string
	TipColor        output.Color
	TipBG           output.Color
	ShowHelp        bool
	Help            SelHelpTextFunc
	HelpColor       output.Color
	HelpBG          output.Color
	Valid           func(sels []int) error
	ValidColor      output.Color
	ValidBG         output.Color
	SuggestColor    output.Color
	SuggestBG       output.Color
	SelSuggestColor output.Color
	SelSuggestBG    output.Color
	DescColor       output.Color
	DescBG          output.Color
	SelDescColor    output.Color
	SelDescBG       output.Color
	BarColor        output.Color
	BarBG           output.Color
	FinishText      SelFinishTextFunc
	ShowItem        bool
	ResultColor     output.Color
	ResultBG        output.Color
	Defaults        []int
}

func WithSelectOptionOptions(v ...*completion.Suggest) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.Options
		cc.Options = v
		return WithSelectOptionOptions(previous...)
	}
}

func WithSelectOptionRows(v int) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.Rows
		cc.Rows = v
		return WithSelectOptionRows(previous)
	}
}

func WithSelectOptionOnFinish(v func(sels []int)) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.OnFinish
		cc.OnFinish = v
		return WithSelectOptionOnFinish(previous)
	}
}

func WithSelectOptionMulti(v bool) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.Multi
		cc.Multi = v
		return WithSelectOptionMulti(previous)
	}
}

func WithSelectOptionFinish(v input.Key) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.Finish
		cc.Finish = v
		return WithSelectOptionFinish(previous)
	}
}

func WithSelectOptionCancel(v input.Key) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.Cancel
		cc.Cancel = v
		return WithSelectOptionCancel(previous)
	}
}

func WithSelectOptionTip(v string) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.Tip
		cc.Tip = v
		return WithSelectOptionTip(previous)
	}
}

func WithSelectOptionTipColor(v output.Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.TipColor
		cc.TipColor = v
		return WithSelectOptionTipColor(previous)
	}
}

func WithSelectOptionTipBG(v output.Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.TipBG
		cc.TipBG = v
		return WithSelectOptionTipBG(previous)
	}
}

func WithSelectOptionShowHelp(v bool) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.ShowHelp
		cc.ShowHelp = v
		return WithSelectOptionShowHelp(previous)
	}
}

func WithSelectOptionHelp(v SelHelpTextFunc) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.Help
		cc.Help = v
		return WithSelectOptionHelp(previous)
	}
}

func WithSelectOptionHelpColor(v output.Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.HelpColor
		cc.HelpColor = v
		return WithSelectOptionHelpColor(previous)
	}
}

func WithSelectOptionHelpBG(v output.Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.HelpBG
		cc.HelpBG = v
		return WithSelectOptionHelpBG(previous)
	}
}

func WithSelectOptionValid(v func(sels []int) error) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.Valid
		cc.Valid = v
		return WithSelectOptionValid(previous)
	}
}

func WithSelectOptionValidColor(v output.Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.ValidColor
		cc.ValidColor = v
		return WithSelectOptionValidColor(previous)
	}
}

func WithSelectOptionValidBG(v output.Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.ValidBG
		cc.ValidBG = v
		return WithSelectOptionValidBG(previous)
	}
}

func WithSelectOptionSuggestColor(v output.Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.SuggestColor
		cc.SuggestColor = v
		return WithSelectOptionSuggestColor(previous)
	}
}

func WithSelectOptionSuggestBG(v output.Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.SuggestBG
		cc.SuggestBG = v
		return WithSelectOptionSuggestBG(previous)
	}
}

func WithSelectOptionSelSuggestColor(v output.Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.SelSuggestColor
		cc.SelSuggestColor = v
		return WithSelectOptionSelSuggestColor(previous)
	}
}

func WithSelectOptionSelSuggestBG(v output.Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.SelSuggestBG
		cc.SelSuggestBG = v
		return WithSelectOptionSelSuggestBG(previous)
	}
}

func WithSelectOptionDescColor(v output.Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.DescColor
		cc.DescColor = v
		return WithSelectOptionDescColor(previous)
	}
}

func WithSelectOptionDescBG(v output.Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.DescBG
		cc.DescBG = v
		return WithSelectOptionDescBG(previous)
	}
}

func WithSelectOptionSelDescColor(v output.Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.SelDescColor
		cc.SelDescColor = v
		return WithSelectOptionSelDescColor(previous)
	}
}

func WithSelectOptionSelDescBG(v output.Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.SelDescBG
		cc.SelDescBG = v
		return WithSelectOptionSelDescBG(previous)
	}
}

func WithSelectOptionBarColor(v output.Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.BarColor
		cc.BarColor = v
		return WithSelectOptionBarColor(previous)
	}
}

func WithSelectOptionBarBG(v output.Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.BarBG
		cc.BarBG = v
		return WithSelectOptionBarBG(previous)
	}
}

func WithSelectOptionFinishText(v SelFinishTextFunc) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.FinishText
		cc.FinishText = v
		return WithSelectOptionFinishText(previous)
	}
}

func WithSelectOptionShowItem(v bool) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.ShowItem
		cc.ShowItem = v
		return WithSelectOptionShowItem(previous)
	}
}

func WithSelectOptionResultColor(v output.Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.ResultColor
		cc.ResultColor = v
		return WithSelectOptionResultColor(previous)
	}
}

func WithSelectOptionResultBG(v output.Color) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.ResultBG
		cc.ResultBG = v
		return WithSelectOptionResultBG(previous)
	}
}

func WithSelectOptionDefaults(v ...int) SelectOption {
	return func(cc *SelectOptions) SelectOption {
		previous := cc.Defaults
		cc.Defaults = v
		return WithSelectOptionDefaults(previous...)
	}
}

// SetOption modify options
func (cc *SelectOptions) SetOption(opt SelectOption) {
	_ = opt(cc)
}

// ApplyOption modify options
func (cc *SelectOptions) ApplyOption(opts ...SelectOption) {
	for _, opt := range opts {
		_ = opt(cc)
	}
}

// GetSetOption modify and get last option
func (cc *SelectOptions) GetSetOption(opt SelectOption) SelectOption {
	return opt(cc)
}

// SelectOption option define
type SelectOption func(cc *SelectOptions) SelectOption

// NewSelectOptions create options instance.
func NewSelectOptions(opts ...SelectOption) *SelectOptions {
	cc := newDefaultSelectOptions()
	for _, opt := range opts {
		_ = opt(cc)
	}
	if watchDogSelectOptions != nil {
		watchDogSelectOptions(cc)
	}
	return cc
}

// InstallSelectOptionsWatchDog install watch dog
func InstallSelectOptionsWatchDog(dog func(cc *SelectOptions)) {
	watchDogSelectOptions = dog
}

var watchDogSelectOptions func(cc *SelectOptions)

// newDefaultSelectOptions new option with default value
func newDefaultSelectOptions() *SelectOptions {
	cc := &SelectOptions{
		Options:         nil,
		Rows:            5,
		OnFinish:        nil,
		Multi:           false,
		Finish:          input.Enter,
		Cancel:          input.ControlC,
		Tip:             "",
		TipColor:        output.Yellow,
		TipBG:           output.DefaultColor,
		ShowHelp:        false,
		Help:            defaultSelHelpText,
		HelpColor:       output.DefaultColor,
		HelpBG:          output.DefaultColor,
		Valid:           nil,
		ValidColor:      output.Red,
		ValidBG:         output.DefaultColor,
		SuggestColor:    output.White,
		SuggestBG:       output.Cyan,
		SelSuggestColor: output.Black,
		SelSuggestBG:    output.Turquoise,
		DescColor:       output.Black,
		DescBG:          output.Turquoise,
		SelDescColor:    output.White,
		SelDescBG:       output.Cyan,
		BarColor:        output.DarkGray,
		BarBG:           output.Cyan,
		FinishText:      defaultSelFinishText,
		ShowItem:        true,
		ResultColor:     output.Blue,
		ResultBG:        output.DefaultColor,
		Defaults:        nil,
	}
	return cc
}
